env:
  es6: true

plugins:
  - prettier

extends:
  - prettier

rules:
  no-const-assign: 2
  no-dupe-class-members: 2
  no-else-return: 2
  no-lonely-if: 2
  no-unused-expressions: 2
  no-unused-vars: [2, {args: none}]
  no-var: 2
  prefer-const: 2
  prefer-promise-reject-errors: 2
  prettier/prettier: [2, {
      bracketSpacing: false,
      printWidth: 80,
      singleQuote: true,
      trailingComma: es5
    }
  ]

parserOptions:
  sourceType: module
